
import type { Product, Category } from './types';

export const categories: Category[] = [
  { id: 1, name: 'Electronics', image: 'https://picsum.photos/id/1/200/200' },
  { id: 2, name: 'Fashion', image: 'https://picsum.photos/id/103/200/200' },
  { id: 3, name: 'Home', image: 'https://picsum.photos/id/20/200/200' },
  { id: 4, name: 'Books', image: 'https://picsum.photos/id/24/200/200' },
  { id: 5, name: 'Toys', image: 'https://picsum.photos/id/35/200/200' },
  { id: 6, name: 'Grocery', image: 'https://picsum.photos/id/40/200/200' },
];

export const products: Product[] = [
  {
    id: 1,
    name: 'Wireless Bluetooth Headphones',
    description: 'High-fidelity sound with noise-cancellation. Up to 20 hours of battery life. Comfortable over-ear design.',
    price: 99.99,
    originalPrice: 129.99,
    rating: 4.5,
    reviewCount: 1250,
    category: 'Electronics',
    images: ['https://picsum.photos/id/1075/600/600', 'https://picsum.photos/id/1076/600/600', 'https://picsum.photos/id/1077/600/600'],
    stock: 50,
  },
  {
    id: 2,
    name: 'Modern Leather Sofa',
    description: 'A stylish and comfortable sofa for your living room. Made with premium Italian leather.',
    price: 799.00,
    originalPrice: 999.00,
    rating: 4.8,
    reviewCount: 340,
    category: 'Home',
    images: ['https://picsum.photos/id/21/600/600', 'https://picsum.photos/id/22/600/600'],
    stock: 15,
  },
  {
    id: 3,
    name: 'Men\'s Classic Fit T-Shirt',
    description: 'A comfortable and stylish t-shirt made from 100% premium cotton. Available in various colors.',
    price: 24.50,
    originalPrice: 29.99,
    rating: 4.2,
    reviewCount: 5600,
    category: 'Fashion',
    images: ['https://picsum.photos/id/102/600/600', 'https://picsum.photos/id/104/600/600'],
    stock: 200,
  },
  {
    id: 4,
    name: 'The Alchemist by Paulo Coelho',
    description: 'An allegorical novel by Paulo Coelho that has become a modern classic.',
    price: 12.99,
    originalPrice: 15.00,
    rating: 4.9,
    reviewCount: 25000,
    category: 'Books',
    images: ['https://picsum.photos/id/25/600/600'],
    stock: 150,
  },
  {
    id: 5,
    name: 'Smart Fitness Tracker Watch',
    description: 'Track your steps, heart rate, and sleep patterns. Waterproof design with a color touch screen.',
    price: 49.99,
    originalPrice: 79.99,
    rating: 4.6,
    reviewCount: 8900,
    category: 'Electronics',
    images: ['https://picsum.photos/id/55/600/600', 'https://picsum.photos/id/56/600/600'],
    stock: 80,
  },
  {
    id: 6,
    name: 'Organic Arabica Coffee Beans',
    description: 'Medium roast, whole bean coffee with notes of chocolate and caramel. Sourced from fair-trade farms.',
    price: 18.75,
    originalPrice: 22.00,
    rating: 4.7,
    reviewCount: 950,
    category: 'Grocery',
    images: ['https://picsum.photos/id/30/600/600'],
    stock: 100,
  },
    {
    id: 7,
    name: 'Denim Jacket for Women',
    description: 'A timeless denim jacket with a classic fit. Perfect for layering in any season.',
    price: 65.00,
    originalPrice: 80.00,
    rating: 4.4,
    reviewCount: 1120,
    category: 'Fashion',
    images: ['https://picsum.photos/id/111/600/600', 'https://picsum.photos/id/112/600/600'],
    stock: 75,
  },
  {
    id: 8,
    name: 'Non-Stick Cookware Set',
    description: '10-piece cookware set with a durable non-stick coating. Includes pans, pots, and utensils.',
    price: 149.99,
    originalPrice: 199.99,
    rating: 4.7,
    reviewCount: 2300,
    category: 'Home',
    images: ['https://picsum.photos/id/29/600/600'],
    stock: 30,
  },
];

export const banners = [
    { id: 1, image: 'https://picsum.photos/id/12/1200/400', title: 'Big Holiday Sale!', subtitle: 'Up to 50% off on electronics' },
    { id: 2, image: 'https://picsum.photos/id/15/1200/400', title: 'New Fashion Arrivals', subtitle: 'Discover the latest trends' },
];
