
import type { Product, Category } from './types';

export const categories: Category[] = [
  { id: 1, name: 'Electronics', image: 'https://picsum.photos/id/1/200/200' },
  { id: 2, name: 'Fashion', image: 'https://picsum.photos/id/103/200/200' },
  { id: 3, name: 'Home', image: 'https://picsum.photos/id/20/200/200' },
  { id: 4, name: 'Books', image: 'https://picsum.photos/id/24/200/200' },
  { id: 5, name: 'Toys', image: 'https://picsum.photos/id/35/200/200' },
  { id: 6, name: 'Grocery', image: 'https://picsum.photos/id/40/200/200' },
];

export const products: Product[] = [
    {
        id: 1,
        name: "Aura Smartwatch Series 7",
        description: "Stay connected and track your fitness with the Aura Smartwatch. Features a stunning edge-to-edge display, advanced health sensors, and seamless integration with your smartphone.",
        price: 18999,
        originalPrice: 24999,
        rating: 4.8,
        reviewCount: 256,
        category: "Electronics",
        images: [
            "https://picsum.photos/id/180/600/600",
            "https://picsum.photos/id/181/600/600",
            "https://picsum.photos/id/182/600/600",
        ],
        stock: 40,
    },
    {
        id: 2,
        name: "Classic Leather Jacket",
        description: "A timeless biker-style jacket crafted from 100% genuine leather. Features a comfortable lining, durable zippers, and a sleek, modern fit.",
        price: 7999,
        originalPrice: 12999,
        rating: 4.9,
        reviewCount: 180,
        category: "Fashion",
        images: [
            "https://picsum.photos/id/1060/600/600",
            "https://picsum.photos/id/1061/600/600",
        ],
        stock: 25,
        sizes: ["M", "L", "XL", "XXL"],
    },
    {
        id: 3,
        name: "Scented Candle Set (3-Pack)",
        description: "Transform your home's ambiance with our set of three soy wax scented candles. Includes Lavender, Ocean Breeze, and Sandalwood scents.",
        price: 1299,
        originalPrice: 1999,
        rating: 4.6,
        reviewCount: 95,
        category: "Home",
        images: [
            "https://picsum.photos/id/106/600/600",
            "https://picsum.photos/id/119/600/600",
        ],
        stock: 80,
    },
    {
        id: 4,
        name: "Pro Gamer RGB Mouse",
        description: "Gain a competitive edge with this high-precision gaming mouse. Features customizable RGB lighting, 16,000 DPI sensor, and 8 programmable buttons.",
        price: 3499,
        originalPrice: 5999,
        rating: 4.7,
        reviewCount: 150,
        category: "Electronics",
        images: [
            "https://picsum.photos/id/1072/600/600",
        ],
        stock: 60,
    },
    {
        id: 5,
        name: "Organic Himalayan Green Tea",
        description: "A refreshing and healthy blend of organic green tea leaves sourced directly from the Himalayas. Rich in antioxidants. 100 tea bags.",
        price: 499,
        originalPrice: 799,
        rating: 4.9,
        reviewCount: 320,
        category: "Grocery",
        images: [
            "https://picsum.photos/id/225/600/600",
        ],
        stock: 150,
    },
    {
        id: 6,
        name: "Men's Running Shoes",
        description: "Lightweight and breathable running shoes designed for maximum comfort and performance. Features a cushioned sole and excellent grip.",
        price: 4599,
        originalPrice: 8999,
        rating: 4.5,
        reviewCount: 210,
        category: "Fashion",
        images: [
            "https://picsum.photos/id/21/600/600",
            "https://picsum.photos/id/1078/600/600",
        ],
        stock: 70,
        sizes: ["8", "9", "10", "11"],
    },
    {
        id: 7,
        name: "Wooden Building Blocks Set",
        description: "A classic 100-piece wooden block set for kids. Encourages creativity, fine motor skills, and imaginative play. Made with non-toxic paint.",
        price: 2499,
        originalPrice: 3499,
        rating: 4.8,
        reviewCount: 112,
        category: "Toys",
        images: [
            "https://picsum.photos/id/199/600/600",
        ],
        stock: 50,
    },
    {
        id: 8,
        name: "The Midnight Library",
        description: "A novel by Matt Haig, a No. 1 Sunday Times bestseller. A heartwarming story about choices, regrets, and the infinite possibilities of life.",
        price: 399,
        originalPrice: 699,
        rating: 4.9,
        reviewCount: 850,
        category: "Books",
        images: [
            "https://picsum.photos/id/30/600/600",
        ],
        stock: 200,
    },
];
